sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=25.2

addons:
  apt:
    packages:
    - aspell
    - aspell-en

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - emacs=$EMACS make update
  - emacs=$EMACS make compile
  - emacs=$EMACS make test
  - emacs=$EMACS make evil-test
